version: '2.1'
services:
  postgres:
    container_name: postgres
    image: 'postgres:10.3-alpine'
    ports:
    - 5432:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - 80:80
    environment:
    - PGADMIN_DEFAULT_EMAIL=user@domain.com
    - PGADMIN_DEFAULT_PASSWORD=SuperSecret