api:
  timezone: UTC
spring:
  datasource:
    url: ${POSTGRES_JDBC_URL:jdbc:postgresql://localhost:5432/postgres}
    username: postgres
    password: ${POSTGRES_PASSWORD:pass}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    favicon:
      enabled: false
  resources:
    add-mappings: false